"""Added course_image  column in course table

Revision ID: 03d4eed686e3
Revises: ece36d1acd28
Create Date: 2024-05-09 17:36:02.115844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03d4eed686e3'
down_revision = 'ece36d1acd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_image', sa.String(length=300), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_column('course_image')

    # ### end Alembic commands ###
