"""Modified

Revision ID: 654a02c1e93f
Revises: ba0f3fc23f0a
Create Date: 2024-04-23 18:53:33.161605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654a02c1e93f'
down_revision = 'ba0f3fc23f0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=True),
    sa.Column('tee_time_id', sa.Integer(), nullable=True),
    sa.Column('booked_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['tee_time_id'], ['tee_time.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    with op.batch_alter_table('course', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('club_id')

    op.drop_table('booking')
    op.drop_table('club')
    # ### end Alembic commands ###
