"""Modified booking tables to allow for more information

Revision ID: 79fdf6e4f4ed
Revises: 6fadeee70445
Create Date: 2024-05-06 17:32:16.896252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79fdf6e4f4ed'
down_revision = '6fadeee70445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
