"""empty message

Revision ID: 94b330129769
Revises: 2217c3494fb6
Create Date: 2024-04-24 20:30:12.748692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94b330129769'
down_revision = '2217c3494fb6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass  # Since you manually created the column, there's nothing to do here.

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tee_time', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_slots', sa.INTEGER(), nullable=False))  # Adjust if needed

    # ### end Alembic commands ###
