"""Modified Member Table to include relational reference to club_id

Revision ID: ece36d1acd28
Revises: 91b91456be3c
Create Date: 2024-05-07 17:55:21.910658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ece36d1acd28'
down_revision = '91b91456be3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('club_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'club', ['club_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('club_id')

    # ### end Alembic commands ###
